### ISSUE TITLE
Missing clause in section claiming The Johnno isn't perfect

### ISSUE THREAD

**Issue by jrolfs** [johnnonolan/ManagerReadMe#1]
> If you feel like our team is not adhering to these **`[¿ ⋯ ?]`**

Perhaps an attempt to demonstrate humanity/imperfection?

Nice try, 🤖

**Comment by johnnonolan** [comment]
I fail CAPTCHA.

**Comment by johnnonolan** [comment]
Resolved in https://github.com/johnnonolan/ReadMe/commit/09ce73e554376a9c149c9c519f3a55dc9887cdf8
