### ISSUE TITLE
Lead by example?

### ISSUE THREAD

**Issue by corlobepy** [johnnonolan/ManagerReadMe#2]
> Unless there is an emergency I can't guarantee I will respond until the next working day. If I contact you, I don't expect that you do the same. If there is an emergency, feel free to Page me. If I contact you in an emergency, (e.g. production system down) I expect you to care enough.

how can you expect your team to respond immediately outside of working hours when you won't if we contact you?
It's important to recognize that there is something else besides work, especially outside of working hours, or while in holidays. At least in our team, people's life are not dependent on our work.

**Comment by johnnonolan** [comment]
That's what I am trying to communicate. Which isn't clear enough obviously.

What I want to say is  "I respect your free time, feel free to call me if you really need to. Most things can wait but if they can't, call me. It's cool."

Does that make sense @corlobepy ?

I think i need to re-write that part either way :)

**Comment by corlobepy** [comment]
That makes more sense and sounds already better than your original wordings.

**Comment by johnnonolan** [comment]
Think I've tackled this in https://github.com/johnnonolan/ReadMe/commit/09ce73e554376a9c149c9c519f3a55dc9887cdf8

Is that better @corlobepy?
