### ISSUE TITLE
Johnno vs Robot?

### ISSUE THREAD

**Issue by elhamrastkhadiv** [johnnonolan/ManagerReadMe#3]
hmm, I think this readme does not represent who you are. It sounds like a robot or someone I do not like to work with.

**Comment by johnnonolan** [comment]
thanks. I need some writing lessons then. Johnnobot's algorithms say "let's talk".

**Comment by johnnonolan** [comment]
Can you take a look at the changes i made in https://github.com/johnnonolan/ReadMe/commit/09ce73e554376a9c149c9c519f3a55dc9887cdf8? @elhamrastkhadiv

**Comment by johnnonolan** [comment]
Closing as per off Github endorsement.
