### ISSUE TITLE
A bit intimidating for a new team member

### ISSUE THREAD

**Issue by daveywavy** [johnnonolan/ManagerReadMe#4]
"If you don't care about these things, you won't fit on our team."

I can understand where you are coming from on this. But someone who joins the team may be just learning to care about these things. Is there some gentler language you could use?

**Comment by duereg** [comment]
I was going to make the same comment.

**Comment by johnnonolan** [comment]
Yeah I thought carefully about this one. I'm torn between setting expectations, I want the bar to be that high and being warmer.  I wonder if it's incongruous, as you know my style.  

I try not to intimidate...
![coach gif 9](https://user-images.githubusercontent.com/101177/43543892-3381b8c8-9586-11e8-811b-94b2f90390a3.gif)

**Comment by johnnonolan** [comment]
Softened tone in: https://github.com/johnnonolan/ManagerReadMe/commit/c28335f9c63747f68f0c4adaee004271009556c7
